services:
  api-node:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        AMBIENTE: local
    container_name: api-node
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - internal
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-proxy"
      - "traefik.http.routers.api-node.entrypoints=http" 
      - "traefik.http.routers.api-node.rule=Host(`api-node.cloud.local`)"
      - "traefik.http.middlewares.api-node-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.api-node.middlewares=api-node-https-redirect"
      - "traefik.http.routers.api-node-secure.rule=Host(`api-node.cloud.local`)"
      - "traefik.http.routers.api-node-secure.entrypoints=https"
      - "traefik.http.routers.api-node-secure.tls=true"
      - "traefik.http.services.api-node-secure.loadbalancer.server.port=3000"

networks:
  traefik-proxy:
    external: true
  internal:
    external: true