services:
  local-myurl:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: local-myurl
    restart: unless-stopped
    env_file: etc/config/local.env
    networks:
      - internal
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-proxy"
      - "traefik.http.routers.myurl.entrypoints=http"
      - "traefik.http.routers.myurl.rule=Host(`myurl.cloud.local`)"
      - "traefik.http.middlewares.myurl-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.myurl.middlewares=myurl-https-redirect"
      - "traefik.http.routers.myurl-secure.rule=Host(`myurl.cloud.local`)"
      - "traefik.http.routers.myurl-secure.entrypoints=https"
      - "traefik.http.routers.myurl-secure.tls=true"
      - "traefik.http.services.myurl.loadbalancer.server.port=3000"

networks:
  traefik-proxy:
    external: true
  internal:
    external: true